version: '3'
services:
  arangodb:
    image: arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=password
    ports:
      - 8529:8529
    volumes:
      - arangodb_data:/var/lib/arangodb3

volumes:
  arangodb_data: